{% set name = "streamable" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ebonnal/streamable/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d1d50deeb85dfa8b53c516136107a9988e55f04134310dd0acd02e102ae27c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - streamable
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ebonnal/streamable
  summary: Stream-like manipulation of iterables
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
