{% set name = "streamable" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ebonnal/streamable/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b0f88b834dcf7e701293052c092beb0a4aee803d7c5d17557c01141f049a627

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - streamable
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ebonnal/streamable
  summary: Stream-like manipulation of iterables
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
