{% set name = "streamable" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ebonnal/streamable/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 696ef6f8f43e614dabe7f148067ad1bd10a7d6f7ab156e02d7d143cc772c1680

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - streamable
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ebonnal/streamable
  summary: Stream-like manipulation of iterables
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
